DROP TABLE IF EXISTS ODONTOLOGOS;

CREATE TABLE ODONTOLOGOS(ID INT AUTO_INCREMENT PRIMARY KEY, MATRICULA INT NOT NULL, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL);



-- Odontólogos creados para test de la base de datos --

INSERT INTO ODONTOLOGOS(MATRICULA, NOMBRE, APELLIDO) VALUES (123456, 'Sebas', 'Ruiz'), (654321, 'Maria', 'Riveros'), (098765, 'Marcela', 'Daza');